# Generated by Django 5.0.6 on 2026-06-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DelegationCeiling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=128)),
                ('authority', models.CharField(max_length=128)),
                ('ceiling_cr', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['-ceiling_cr'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twofa_mandatory', models.BooleanField(default=True)),
                ('password_min_length', models.IntegerField(default=12)),
                ('password_rotation_days', models.IntegerField(default=90)),
                ('session_timeout_min', models.IntegerField(default=30)),
                ('data_residency', models.CharField(default='India-only · locked', max_length=64)),
                ('encryption', models.CharField(default='TLS 1.2+ in transit · AES-256 at rest', max_length=128)),
                ('retention_days', models.IntegerField(default=365)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='last_active',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(default='Active', max_length=16),
        ),
        migrations.AddField(
            model_name='profile',
            name='twofa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='twofa_secret',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='profile',
            name='unit',
            field=models.CharField(blank=True, default='NeGD', max_length=64),
        ),
    ]
