# Generated by Django 5.0.6 on 2026-06-21 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drafting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('instrument', models.CharField(blank=True, max_length=8)),
                ('source_text', models.TextField(blank=True)),
                ('status', models.CharField(default='open', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('draft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='drafting.draft')),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=128)),
                ('category', models.CharField(max_length=24)),
                ('severity', models.CharField(default='Medium', max_length=16)),
                ('issue', models.TextField()),
                ('original_text', models.TextField(blank=True)),
                ('suggested_text', models.TextField(blank=True)),
                ('rationale', models.TextField(blank=True)),
                ('citation', models.CharField(blank=True, max_length=256)),
                ('origin', models.CharField(default='llm', max_length=16)),
                ('status', models.CharField(default='open', max_length=16)),
                ('final_text', models.TextField(blank=True)),
                ('clause_id', models.IntegerField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='review.reviewsession')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
