# Generated by Django 5.0.6 on 2026-06-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='span',
            field=models.TextField(blank=True),
        ),
    ]
