# Generated by Django 5.0.6 on 2026-06-21 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('citation', models.CharField(max_length=128)),
                ('raw_text', models.TextField()),
                ('classified_framework', models.CharField(blank=True, max_length=64)),
                ('classified_type', models.CharField(blank=True, max_length=64)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('embedding', models.JSONField(blank=True, default=list)),
                ('duplicate_score', models.FloatField(default=0.0)),
                ('conflict_score', models.FloatField(default=0.0)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conflicts_with', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='knowledge.chunk')),
                ('created_chunk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='knowledge.chunk')),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='knowledge.chunk')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_jobs', to='knowledge.knowledgesource')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
