# Generated by Django 5.0.6 on 2026-06-22 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_ingestionjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('body', models.TextField(blank=True)),
                ('tone', models.CharField(default='warn', max_length=8)),
                ('framework', models.CharField(blank=True, max_length=64)),
                ('action_label', models.CharField(default='Review impact', max_length=64)),
                ('affected_count', models.IntegerField(default=0)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=256)),
                ('published_by', models.CharField(default='knowledge.admin', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='knowledge.knowledgesource')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
