# Generated by Django 5.0.6 on 2026-06-22 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drafting', '0002_draft_locked_draft_updated_at_draft_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finding_key', models.CharField(max_length=128)),
                ('framework', models.CharField(blank=True, max_length=64)),
                ('rule', models.CharField(blank=True, max_length=256)),
                ('justification', models.TextField()),
                ('actor', models.CharField(default='demo.drafter', max_length=64)),
                ('role', models.CharField(default='drafter', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_overrides', to='drafting.draft')),
            ],
            options={
                'ordering': ['-id'],
                'unique_together': {('draft', 'finding_key')},
            },
        ),
    ]
