# Generated by Django 5.0.6 on 2026-06-21 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('instrument', models.CharField(choices=[('RFP', 'RFP'), ('RFQ', 'RFQ'), ('RFE', 'RFE'), ('EOI', 'EOI')], default='RFP', max_length=8)),
                ('category', models.CharField(choices=[('Goods', 'Goods'), ('Consulting', 'Consulting'), ('Non-Consulting', 'Non-Consulting')], default='Goods', max_length=24)),
                ('estimated_value_cr', models.FloatField(default=0)),
                ('selection_method', models.CharField(blank=True, default='QCBS', max_length=32)),
                ('brief', models.TextField(blank=True)),
                ('namespaces', models.JSONField(blank=True, default=list)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clause_type', models.CharField(max_length=64)),
                ('text', models.TextField(blank=True)),
                ('citations', models.JSONField(blank=True, default=list)),
                ('confidence', models.CharField(default='Low', max_length=16)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('grounded', models.BooleanField(default=True)),
                ('rationale', models.TextField(blank=True)),
                ('model', models.CharField(blank=True, max_length=64)),
                ('prompt_version', models.CharField(default='v1', max_length=32)),
                ('accepted', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='drafting.draft')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
