# Generated by Django 5.0.6 on 2026-06-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drafting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='draft',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='draft',
            name='version',
            field=models.IntegerField(default=3),
        ),
    ]
