# Generated by Django 5.0.6 on 2026-06-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drafting', '0002_draft_locked_draft_updated_at_draft_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('instrument', models.CharField(choices=[('RFP', 'RFP'), ('RFQ', 'RFQ'), ('RFE', 'RFE'), ('EOI', 'EOI')], default='RFP', max_length=8)),
                ('category', models.CharField(choices=[('Goods', 'Goods'), ('Consulting', 'Consulting'), ('Non-Consulting', 'Non-Consulting')], default='Goods', max_length=24)),
                ('selection_method', models.CharField(blank=True, default='', max_length=32)),
                ('version', models.CharField(default='v2026.06', max_length=32)),
                ('sections', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True)),
                ('recommended', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='draft',
            name='template_key',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
