# Generated by Django 5.0.6 on 2026-06-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drafting', '0003_template_draft_template_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoilerplateClause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clause_type', models.CharField(max_length=64)),
                ('kind', models.CharField(choices=[('boilerplate', 'boilerplate'), ('parameterized', 'parameterized')], default='boilerplate', max_length=16)),
                ('framework', models.CharField(blank=True, max_length=32)),
                ('citation', models.CharField(blank=True, max_length=128)),
                ('version', models.CharField(default='v2026.06', max_length=32)),
                ('heading', models.CharField(blank=True, max_length=128)),
                ('body', models.TextField()),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['clause_type'],
                'unique_together': {('clause_type', 'version')},
            },
        ),
    ]
