# Generated by Django 5.0.6 on 2026-06-21 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('instrument', models.CharField(default='RFP', max_length=8)),
                ('category', models.CharField(default='Goods', max_length=24)),
                ('estimated_value_cr', models.FloatField(default=0)),
                ('year', models.IntegerField(default=2025)),
                ('summary', models.TextField(blank=True)),
                ('full_text', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('embedding', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalClause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clause_type', models.CharField(max_length=64)),
                ('text', models.TextField()),
                ('citation', models.CharField(blank=True, max_length=256)),
                ('embedding', models.JSONField(blank=True, default=list)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='similarity.historicaldocument')),
            ],
        ),
    ]
