# Generated by Django 5.0.6 on 2026-06-21 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drafting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clause_ref', models.CharField(blank=True, max_length=64)),
                ('action', models.CharField(max_length=24)),
                ('clause_text', models.TextField(blank=True)),
                ('citation', models.CharField(blank=True, max_length=256)),
                ('kb_version', models.CharField(blank=True, max_length=64)),
                ('confidence', models.CharField(blank=True, max_length=16)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('model', models.CharField(blank=True, max_length=64)),
                ('prompt_version', models.CharField(blank=True, max_length=32)),
                ('actor', models.CharField(default='demo.drafter', max_length=64)),
                ('role', models.CharField(default='drafter', max_length=32)),
                ('justification', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prev_hash', models.CharField(blank=True, max_length=64)),
                ('record_hash', models.CharField(blank=True, max_length=64)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_records', to='drafting.draft')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
